hmrc/awrs-lookup-frontend

- app/uk/gov/hmrc/awrslookup/frontendAppConfig.scala
- conf/application.conf
[FIX-CONFIG] - fix config for contact frontend service
> fix config for contact frontend service

- app/uk/gov/hmrc/awrslookup/connectors/LookupConnector.scala
- public/stylesheets/custom.css
[AWRS-1930] - Format String Error - graceful degredation for status 400
> AWRS-1930 - Format String Error - graceful degredation for status 400

- app/uk/gov/hmrc/awrslookup/forms/prevalidation/PrevalidationAPI.scala
AWRS-1930 - implement xssFilter
> AWRS-1930 - implement xssFilter

- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry_compact.scala.html
[AWRS-1930] - encode search string
> [AWRS-1930] - encode search string

- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry_compact.scala.html
- public/stylesheets/custom.css
[AWRS-1948] - H2 on multi results page
> [AWRS-1948] - H2 on multi results page

- app/uk/gov/hmrc/awrslookup/views/lookup/common/no_result_warning.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_main.scala.html
- public/stylesheets/custom.css
[AWRS-1949] - spacing and reformatting no results page
> [AWRS-1949] - spacing

- app/uk/gov/hmrc/awrslookup/views/lookup/search/results_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/search_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_no_results.scala.html
[AWRS-1978] - hide search bar from print
> [AWRS-1978] - hide search bar from print

- app/uk/gov/hmrc/awrslookup/views/helpers/awrsInputTypeText.scala.html
[AWRS-LOOKUP-FRONTEND] - Fix aria label
> [AWRS-LOOKUP-FRONTEND] - Fix aria label

- app/uk/gov/hmrc/awrslookup/views/helpers/awrsInputTypeText.scala.html
> AWRS-1994 - Aria Amends

- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry.scala.html
- public/stylesheets/custom.css
[AWRS-1994] - Amend H1 Style for Single Result Page
> [AWRS-1994] - Amend H1 Style for Single Result Page

- app/uk/gov/hmrc/awrslookup/frontendGlobal.scala
- conf/application.conf
- project/FrontendBuild.scala
[AWRS-1995] - configure security headers
> [AWRS-1995] - configure security headers

- app/uk/gov/hmrc/awrslookup/views/lookup/search/results_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_no_results.scala.html
Use GA SEND for GA Event Tracking
> Use GA SEND for GA Event Tracking

- conf/application.conf
[AWRS-2106] correct feedback survey service callback url
> [AWRS-2106] correct feedback survey service callback url

- app/uk/gov/hmrc/awrslookup/views/html/helpers/package.scala
[AWRS-2116] - apply Europe/London timezone to date/time format
> [AWRS-2116] - apply Europe/London timezone to date/time format

- public/javascripts/awrs.js
[AWRS-2004] - Removed focus from query box on page load
> [AWRS-2004] - Removed focus from query box on page load

- app/uk/gov/hmrc/awrslookup/models/SearchResult.scala
- app/uk/gov/hmrc/awrslookup/utils/AwrsDateFormatter.scala
- app/uk/gov/hmrc/awrslookup/views/html/helpers/package.scala
- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry.scala.html
- test/uk/gov/hmrc/awrslookup/views/html/helpers/packageTest.scala
[AWRS-2076] - Remove leading 0s in dates
> [AWRS-2076] - Remove leading 0s in dates

- app/uk/gov/hmrc/awrslookup/views/helpers/searchDate.scala.html
- app/uk/gov/hmrc/awrslookup/views/html/helpers/package.scala
- test/uk/gov/hmrc/awrslookup/views/html/helpers/packageTest.scala
[AWRS-2074] - Format - time/date
> [AWRS-2074] - Format - time/date

- app/uk/gov/hmrc/awrslookup/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/awrslookup/views/html/helpers/package.scala
- app/uk/gov/hmrc/awrslookup/views/lookup/common/no_result_warning.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/results_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/search_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_no_results.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/single_result.scala.html
- app/uk/gov/hmrc/awrslookup/views/main_template.scala.html
[AWRS-2003] - css file placement and awrs urn aria label corrections
> [AWRS-2003] - css file placement and awrs urn aria label corrections

- public/javascripts/awrs.js
[AWRS-2002] add tabindex -1 attribute to #content
> [AWRS-2002] add tabindex -1 attribute to #content

- app/uk/gov/hmrc/awrslookup/views/html/helpers/package.scala
[AWRS-2003] - NVDA fix for AWRS URN
> [AWRS-2003] - NVDA fix for AWRS URN

- app/uk/gov/hmrc/awrslookup/views/helpers/awrsInputTypeText.scala.html
- app/uk/gov/hmrc/awrslookup/views/helpers/awrs_urn.scala.html
- conf/messages
[AWRS-2003] - NVDA aria label amends
> [AWRS-2003] - NVDA aria label amends

- app/uk/gov/hmrc/awrslookup/views/helpers/awrsInputTypeText.scala.html
- app/uk/gov/hmrc/awrslookup/views/helpers/awrs_urn.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/common/no_result_warning.scala.html
- conf/messages
- conf/messages.cy
[AWRS-2003] - Replace AWRS URN with Unique Reference Number
> [AWRS-2003] - Replace AWRS URN with Unique Reference Number

- app/uk/gov/hmrc/awrslookup/views/govuk_wrapper.scala.html
[AWRS-2040] - replace ' hex code in page title
> [AWRS-2040] - replace ' hex code in page title

- conf/messages
- conf/messages.cy
[AWRS-2071] - Service name and H1
> [AWRS-2071] - Service name and H1

- project/FrontendBuild.scala
[AWRS-2067] - upgrade bootstrap dependency
> [AWRS-2067] - upgrade bootstrap dependency

- public/javascripts/awrs.js
[AWRS-2003] - Add JS solution for skip to main content.
Removed tabindex="-1" from #content
> [AWRS-2003] - Add JS solution for skip to main content.

- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry.scala.html
- conf/messages
- public/stylesheets/custom.css
> [AWRS-2086] - Group

- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/results/table_row.scala.html
- conf/messages
- conf/messages.cy
> [AWRS-2086] - Lookup Groups

- public/javascripts/awrs.js
[AWRS-2152] - Lookup - Skip to main content
Apply JavaScript fix
> [AWRS-2152] - Lookup - Skip to main content

- app/uk/gov/hmrc/awrslookup/models/SearchResult.scala
[AWRS-2154] - where no start date is present - technical difficulties displayed
> [AWRS-2154] - where no start date is present - technical difficulties displayed

- app/uk/gov/hmrc/awrslookup/views/lookup/common/warning_core.scala.html
Confirmed that no i18n message needed.
> Changed warning alt text to important information

- app/uk/gov/hmrc/awrslookup/controllers/LookupController.scala
- app/uk/gov/hmrc/awrslookup/views/helpers/awrsInputTypeText.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/results_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/search_button.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/search_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_main.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/single_result.scala.html
- conf/messages
[AWRS-2087] - acessibiity - search bar label to read out correctly
> [AWRS-2087] - acessibiity - search bar label to read out correctly

- app/uk/gov/hmrc/awrslookup/views/lookup/common/no_result_warning.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/common/status_warning.scala.html
- public/javascripts/awrs.js
[AWRS-2194] - add data-journey-click attribute for GA tracking
> [AWRS-2194] - add data-journey-click attribute for GA tracking

- conf/messages
- conf/messages.cy
- conf/messages.en
Delete unused messages (English and Welsh versions); unit tests okay.
> DDCNLS-1715

- app/uk/gov/hmrc/awrslookup/frontendAppConfig.scala
- app/uk/gov/hmrc/awrslookup/views/govuk_wrapper.scala.html
DDCNLS-3306: Removed beta banner
> DDCNLS-3306: Removed beta banner

- conf/messages
- conf/messages.cy
@nehadotkannaujia - can you check my code, I have just removed contractions (from the English version) and replaced primes with apostrophes in the Welsh version. Unit tests are okay. Thanks
CARE - do not merge until acceptance tests have been run.
> DDCNLS-1716

- conf/application.conf
DL-2214 updating GA config
**Maintenance** 
Updating config to standard implementation as config should be done within app-config for relevent environments
> DL-2214 update GA config

- app/uk/gov/hmrc/awrslookup/controllers/AwrsLanguageController.scala
- project/FrontendBuild.scala
- project/MicroService.scala
- project/build.properties
- project/plugins.sbt
DL-2714
**Maintenance** 
Dependency and plugin upgrade. Slight adjustment to language controller
Unit tests and ATs run and successful
> DL-2714 Dependency and plugin upgrades

- app/uk/gov/hmrc/awrslookup/views/helpers/fullWidthBanner.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/common/no_result_warning.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/results/awrs_entry.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/results_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search/search_core.scala.html
- app/uk/gov/hmrc/awrslookup/views/lookup/search_no_results.scala.html
- app/uk/gov/hmrc/awrslookup/views/main_template.scala.html
- test/uk/gov/hmrc/awrslookup/views/LookupViewTest.scala
**Accessibility**
Fixing issues identified from Accessibility tool
> DL-2889 Accessibility fixes

- test/uk/gov/hmrc/awrslookup/connectors/LookupConnectorTest.scala
- test/uk/gov/hmrc/awrslookup/controllers/LookupControllerTest.scala
- test/uk/gov/hmrc/awrslookup/forms/test/util/FormValidationTestAPI.scala
- test/uk/gov/hmrc/awrslookup/forms/validation/util/ErrorMessageLookupLookupTest.scala
- test/uk/gov/hmrc/awrslookup/forms/validation/util/ErrorMessageLookupTest.scala
- test/uk/gov/hmrc/awrslookup/forms/validation/util/MappingTest.scala
**Warning fixes**
* Removed warnings from awrs-lookup-frontend
> DL-4001 Fix warnings

- conf/application-json-logger.xml
- conf/logback-test.xml
**Logging update**
* Logging update for awrs-lookup-frontend
> DL-4180 Updated logging config

- app/uk/gov/hmrc/awrslookup/views/govuk_wrapper.scala.html
- conf/application.conf
- project/AppDependencies.scala
DL-3803
**Accessibility** 
Implement accessibility statement (non compliant) for awrs lookup frontend
> DL-3803 accessibility statement implementation

- app/uk/gov/hmrc/awrslookup/FrontendAppConfig.scala
- conf/application.conf
- project/AppDependencies.scala
DL-4217
**Bug fix** (delete as appropriate)
Get help with this page not working on awrs-lookup-frontend
Changes FrontendAppConfig and application.conf to match services that are working
Updated dependencies
Tested locally - screenshot on Jira Ticket
> DL-4217 update config to display get help service

- app/uk/gov/hmrc/awrslookup/controllers/AwrsLanguageController.scala
- project/AppDependencies.scala
**Bug fix**
* Fixed a redirect vulnerability related to the language switching component.
> DL-4598 Fix redirect vulnerability

- app/uk/gov/hmrc/awrslookup/controllers/AwrsLanguageController.scala
- app/uk/gov/hmrc/awrslookup/utils/AwrsDateFormatter.scala
- app/uk/gov/hmrc/awrslookup/utils/ImplicitConversions.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/awrslookup/connectors/LookupConnectorTest.scala
- test/uk/gov/hmrc/awrslookup/controllers/AwrsLanguageControllerTest.scala
- test/uk/gov/hmrc/awrslookup/controllers/LookupControllerTest.scala
- test/uk/gov/hmrc/awrslookup/models/ModelTests.scala
- test/uk/gov/hmrc/awrslookup/services/LookupServiceTest.scala
DL-3290
**Maintenance**
Enhance unit test coverage on awrs-lookup-frontend
Dependency updates
> DL-3290 increase test coverage

- app/views/layout.scala.html
- project/AppDependencies.scala
**Dependency update**
Updated awrs-lookup-frontend to use the latest dependencies to ensure it is using the latest footer code with Welsh translations
> DL-4737 Updated dependencies

- app/config/FrontendAppConfig.scala
- app/views/layout.scala.html
- conf/application.conf
- test/controllers/AwrsLanguageControllerTest.scala
> DL-5048: Add cookie consent/switch off GA

- app/views/helpers/awrsPrintLink.scala.html
- app/views/layout.scala.html
- app/views/lookup/common/no_result_warning.scala.html
- app/views/lookup/common/status_approved.scala.html
- app/views/lookup/common/status_warning.scala.html
- project/AppDependencies.scala
- public/javascripts/awrs.js
-Removed redundant GA code
-Added CSPNonce
> DL-5337: Remove redundant GA code

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
**Dependency update**
* Removed bintray dependency
> DL-5403 Bintray dependency update

- app/CachedStaticHtmlPartialProvider.scala
- project/AppDependencies.scala
- test/connectors/LookupConnectorTest.scala
DL-5785 Bootstrap and Dependency Updates
**New feature**
Bootstrap and dependency updates
> DL-5785 Bootstrap and Dependency Updates

- .gitignore
- app/views/layout.scala.html
- app/views/lookup/common/no_result_warning.scala.html
- app/views/lookup/common/status_approved.scala.html
- app/views/lookup/common/status_warning.scala.html
- app/views/lookup/search/search_core.scala.html
- build.sbt
- conf/app.routes
- project/AppDependencies.scala
- project/build.properties
> DL-6177 Uplift play-frontend-hmrc

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/AwrsLanguageControllerTest.scala
- test/forms/test/util/package.scala
**Maintenance**
Play28 upgrade
Dependency and plugin updates
> DL-6555 play28 upgrade plus dependency and plugin updates

- project/AppDependencies.scala
Upgrade play-frontend-hmrc to latest version
> DL-9490 upgrade play frontend hmrc to latest

- app/views/lookup/common/no_result_warning.scala.html
- conf/messages
- conf/messages.cy
- project/build.properties
- project/plugins.sbt
DL-9104: New wording for Not Found view to fix HTML Validator errors
> DL-9104: New wording for Not Found view

- app/audit/Auditable.scala
- app/connectors/LookupConnector.scala
- app/controllers/LookupController.scala
- app/forms/prevalidation/PrevalidationAPI.scala
- app/forms/validation/util/ConstraintUtil.scala
- app/forms/validation/util/ErrorMessageInterpreter.scala
- app/services/LookupService.scala
- app/utils/AwrsNumberFormatter.scala
- app/utils/LoggingUtils.scala
- app/views/layout.scala.html
- app/views/lookup/common/no_result_warning.scala.html
- app/views/lookup/common/status_approved.scala.html
- app/views/lookup/common/status_warning.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/audit/AuditTest.scala
- test/connectors/LookupConnectorTest.scala
- test/controllers/LookupControllerTest.scala
- test/forms/validation/util/MappingTest.scala
- test/services/LookupServiceTest.scala
- test/services/mocks/MockLookupService.scala
- test/views/LookupViewTest.scala
> DL-10701 Scala upgrade to 2.13.8

- project/AppDependencies.scala
- project/plugins.sbt
Crown implementation play upgrade
> newCrown update dependency

- app/AwrsFrontendErrorHandler.scala
- app/CachedStaticHtmlPartialProvider.scala
- app/connectors/LookupConnector.scala
- app/views/error_template.scala.html
- app/views/layout.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/connectors/LookupConnectorTest.scala
Currently, all is compiling fine and all tests/ATs are passing, service looks fine but DefaultHttpClient might need removing and replacing
> DL-13897: upgrade bootstrap

- app/connectors/LookupConnector.scala
- app/forms/prevalidation/package.scala
- app/forms/validation/util/ConstraintUtil.scala
- app/forms/validation/util/ErrorMessageAPI.scala
- app/forms/validation/util/ErrorMessageFactory.scala
- app/forms/validation/util/ErrorMessageInterpreter.scala
- app/forms/validation/util/ErrorMessagesUtilAPI.scala
- app/utils/LoggingUtils.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/connectors/LookupConnectorTest.scala
- test/controllers/LookupControllerTest.scala
- test/forms/test/util/package.scala
- test/services/LookupServiceTest.scala
- test/services/mocks/MockLookupService.scala
- test/utils/AwrsUnitTestTraits.scala
- test/views/LookupViewTest.scala
**Bug fix**
Update mockito-core to be compatible with JDK21
> fix(DL-15176): Update mockito-core to support JDK21
